//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mach.Kinectomix.LevelEditor.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mach.Kinectomix.LevelEditor.Localization.EditorResources", typeof(EditorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add new level.
        /// </summary>
        public static string AddLevel {
            get {
                return ResourceManager.GetString("AddLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available tiles.
        /// </summary>
        public static string AvailableTiles {
            get {
                return ResourceManager.GetString("AvailableTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinectomix level.
        /// </summary>
        public static string DefaultLevelName {
            get {
                return ResourceManager.GetString("DefaultLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Levels.
        /// </summary>
        public static string GameLevels {
            get {
                return ResourceManager.GetString("GameLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import level....
        /// </summary>
        public static string ImportLevel {
            get {
                return ResourceManager.GetString("ImportLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecule.
        /// </summary>
        public static string Molecule {
            get {
                return ResourceManager.GetString("Molecule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New definition.
        /// </summary>
        public static string NewDefinition {
            get {
                return ResourceManager.GetString("NewDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new levels definition will cancel you modifications on current levels definition.
        ///
        ///Do you want to continue with creating new level definition?.
        /// </summary>
        public static string NewDefinitionPendingChangesText {
            get {
                return ResourceManager.GetString("NewDefinitionPendingChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending changes.
        /// </summary>
        public static string NewDefinitionPendingChangesTitle {
            get {
                return ResourceManager.GetString("NewDefinitionPendingChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open directory with assets for atoms....
        /// </summary>
        public static string OpenAtomsAssetsDirectory {
            get {
                return ResourceManager.GetString("OpenAtomsAssetsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open levels definition....
        /// </summary>
        public static string OpenDefinition {
            get {
                return ResourceManager.GetString("OpenDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening levels definition will cancel you modifications on current levels definition.
        ///
        ///Do you want to continue with opening levels definition?.
        /// </summary>
        public static string OpenDefinitionPendingChangesText {
            get {
                return ResourceManager.GetString("OpenDefinitionPendingChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending changes.
        /// </summary>
        public static string OpenDefinitionPendingChangesTitle {
            get {
                return ResourceManager.GetString("OpenDefinitionPendingChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open directory with assets for fixed tiles....
        /// </summary>
        public static string OpenFixedAssetsDirectory {
            get {
                return ResourceManager.GetString("OpenFixedAssetsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save levels definition as....
        /// </summary>
        public static string SaveDefinitionAs {
            get {
                return ResourceManager.GetString("SaveDefinitionAs", resourceCulture);
            }
        }
    }
}
