//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mach.Kinectomix.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LevelScreenResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LevelScreenResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mach.Kinectomix.Resources.LevelScreenResources", typeof(LevelScreenResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue.
        /// </summary>
        public static string ContinueGame {
            get {
                return ResourceManager.GetString("ContinueGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Level.
        /// </summary>
        public static string DefaultLevelName {
            get {
                return ResourceManager.GetString("DefaultLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Paused.
        /// </summary>
        public static string GamePaused {
            get {
                return ResourceManager.GetString("GamePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to best score.
        /// </summary>
        public static string HighScore {
            get {
                return ResourceManager.GetString("HighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level completed.
        /// </summary>
        public static string LevelCompleted {
            get {
                return ResourceManager.GetString("LevelCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to levels.
        /// </summary>
        public static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main menu.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moves.
        /// </summary>
        public static string Moves {
            get {
                return ResourceManager.GetString("Moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next level.
        /// </summary>
        public static string NextLevel {
            get {
                return ResourceManager.GetString("NextLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play again.
        /// </summary>
        public static string PlayAgain {
            get {
                return ResourceManager.GetString("PlayAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
    }
}
