//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mach.Kinectomix.LevelEditor.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TileResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TileResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mach.Kinectomix.LevelEditor.Localization.TileResources", typeof(TileResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carbon.
        /// </summary>
        public static string Carbon {
            get {
                return ResourceManager.GetString("Carbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transparent.
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fluoride.
        /// </summary>
        public static string Fluoride {
            get {
                return ResourceManager.GetString("Fluoride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hydrogen.
        /// </summary>
        public static string Hydrogen {
            get {
                return ResourceManager.GetString("Hydrogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nitrogen.
        /// </summary>
        public static string Nitrogen {
            get {
                return ResourceManager.GetString("Nitrogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oxygen.
        /// </summary>
        public static string Oxygen {
            get {
                return ResourceManager.GetString("Oxygen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wall.
        /// </summary>
        public static string Wall {
            get {
                return ResourceManager.GetString("Wall", resourceCulture);
            }
        }
    }
}
